language: python

python: "3.5"

dist: bionic

services:
    - docker

cache:
    - pip
    - npm

jobs:
    include:
        - script: cd client && npm install && node --max_old_space_size=4098 node_modules/.bin/grunt build
          name: "client"
        - script: cd server && pip install -r dev-requirements.txt && flake8 && nosetests tests
          name: "server"

